[build]
target = "aarch64-unknown-linux-gnu"

#[target.aarch64-unknown-linux-musl]
#linker = "aarch64-unknown-linux-musl-gcc"

[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-linux-gnu-gcc"
#linker = "aarch64-none-linux-gnu-gcc"
linker = "aarch64-unknown-linux-gnu-gcc"
#linker = "arm-linux-gnueabihf-ld"
#linker = "aarch64-none-elf-gcc"

#rustc-link-search = ["/usr/arm-linux-gnueabihf/lib", "./sysroot/usr/lib"]

#[target.armv7-unknown-linux-gnueabihf.pulse]
#rustc-link-search = ["/usr/arm-linux-gnueabihf/lib", "./sysroot"]
#rustc-link-lib = ["pulse"]
#
#[target.armv7-unknown-linux-gnueabihf.pulse-simple]
#rustc-link-search = ["/usr/arm-linux-gnueabihf/lib", "./sysroot"]
#rustc-link-lib = ["pulse-simple"]
