[package]
name = "robolab"
version = "0.1.0"
authors = ["Leah <github.leah@hrmny.sh>"]
edition = "2018"

build = "build.rs"

#[workspace]
#members = ["stm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }

rand = "0.8"
anyhow = "1"
educe = "0.4"

color-backtrace = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

serde = "1.0"

schemars = "0.8"

sled = "0.34"
palette = "0.6"

#jsonrpc-tcp-server = "17.0.0"
#mio = "0.7.10"

jsonrpc-core = "18"
jsonrpc-ws-server = "18"
jsonrpc-tcp-server = "18"
jsonrpc-pubsub = "18"

rocket = "0.4"
rocket_cors = "0.5"
rocket_contrib = "0.4"

[dependencies.serde_json]
version = "1.0"
features = ["preserve_order", "float_roundtrip"]

[dependencies.rppal]
version = "0.12"
features = ["hal"]

#[dependencies.futures]
#version = "0.3"
#default-features = false
#features = ["alloc"]
#
#[dependencies.tokio]
#version = "1.0.2"
#features = [ "rt-multi-thread", "sync", "signal" ]
#
#[dependencies.warp]
#version = "*"
#git = "https://github.com/seanmonstar/warp"

#nb = "1.0.0"
#smart-leds = "0.3.0"
#embedded-hal = "0.2.3"
#ws2812-timer-delay = "0.3.0"
#ws2812-spi = { version = "0.3.0", features = [ "mosi_idle_high" ] }
#ws2818-rgb-led-spi-driver = { version = "1.0.0", path = "./_pkg/ws28xx" }

#cpal = "0.12.1"
#libpulse-binding = { version = "2.0", default-features = false , features = ["pa_v12"] }
#libpulse-simple-binding = { version = "2.0", default-features = false , features = ["pa_v12"] }


#[dependencies.libpulse-binding]
#version = "2.21"

#[dependencies.vis-core]
#version = "*"
#path = "../_pkg/visualizer2/vis-core"
#default-features = false
#features = [
#    "pulseaudio"
#]
